// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFirst.Data;

#nullable disable

namespace WebApiFirst.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240831195801_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiFirst.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mike",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emily",
                            Surname = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sarah",
                            Surname = "Brown"
                        });
                });

            modelBuilder.Entity("WebApiFirst.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 8, 31, 23, 58, 0, 989, DateTimeKind.Local).AddTicks(2451),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2024, 8, 31, 23, 58, 0, 989, DateTimeKind.Local).AddTicks(2461),
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2024, 8, 31, 23, 58, 0, 989, DateTimeKind.Local).AddTicks(2462),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            OrderDate = new DateTime(2024, 8, 31, 23, 58, 0, 989, DateTimeKind.Local).AddTicks(2463),
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2024, 8, 31, 23, 58, 0, 989, DateTimeKind.Local).AddTicks(2464),
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("WebApiFirst.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 10.00m,
                            Name = "Product 1",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            Discount = 15.00m,
                            Name = "Product 2",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            Discount = 20.00m,
                            Name = "Product 3",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 4,
                            Discount = 25.00m,
                            Name = "Product 4",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 5,
                            Discount = 30.00m,
                            Name = "Product 5",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 6,
                            Discount = 35.00m,
                            Name = "Product 6",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 7,
                            Discount = 40.00m,
                            Name = "Product 7",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 8,
                            Discount = 45.00m,
                            Name = "Product 8",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 9,
                            Discount = 50.00m,
                            Name = "Product 9",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 10,
                            Discount = 55.00m,
                            Name = "Product 10",
                            Price = 550.00m
                        });
                });

            modelBuilder.Entity("WebApiFirst.Entities.Order", b =>
                {
                    b.HasOne("WebApiFirst.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiFirst.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
